<<<<<<< HEAD
# ============================
# CONFIGURACIÓN DE MYSQL
=======
spring.application.name=alkywallet

# ============================

# CONFIGURACIï¿½N DE MYSQL

# CONFIGURACIÃ“N DE MYSQL

>>>>>>> dev
# ============================

spring.datasource.url=jdbc:mysql://localhost:3306/alkywallet_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
<<<<<<< HEAD

=======
allowPublicKeyRetrieval=true&useSSL=false
>>>>>>> dev
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

<<<<<<< HEAD
=======
# ============================
# SPRING SECURITY - Login por defecto
# ============================

spring.security.user.name=user
spring.security.user.password=1234
>>>>>>> dev

# ============================
# PUERTO (opcional)
# ============================

<<<<<<< HEAD
server.port=8080
=======
server.port=8080

>>>>>>> dev
